"""Hand-written pools for fictitious Italian companies and products.

Company names are generated by combining words; any match with a real company is coincidental.
"""

from decimal import Decimal

from pydantic import BaseModel, ConfigDict


class City(BaseModel):
    model_config = ConfigDict(frozen=True)

    name: str
    postal_code: str
    province: str


class Product(BaseModel):
    model_config = ConfigDict(frozen=True)

    code: str
    description: str
    unit: str
    min_price: Decimal
    max_price: Decimal
    vat_rate: Decimal


CITIES = (
    City(name="Milano", postal_code="20121", province="MI"),
    City(name="Roma", postal_code="00184", province="RM"),
    City(name="Torino", postal_code="10121", province="TO"),
    City(name="Bologna", postal_code="40121", province="BO"),
    City(name="Firenze", postal_code="50123", province="FI"),
    City(name="Napoli", postal_code="80133", province="NA"),
    City(name="Bari", postal_code="70121", province="BA"),
    City(name="Verona", postal_code="37121", province="VR"),
    City(name="Padova", postal_code="35122", province="PD"),
    City(name="Brescia", postal_code="25121", province="BS"),
    City(name="Bergamo", postal_code="24122", province="BG"),
    City(name="Modena", postal_code="41121", province="MO"),
    City(name="Parma", postal_code="43121", province="PR"),
    City(name="Genova", postal_code="16121", province="GE"),
    City(name="Ancona", postal_code="60121", province="AN"),
    City(name="Perugia", postal_code="06121", province="PG"),
    City(name="Pescara", postal_code="65121", province="PE"),
    City(name="Treviso", postal_code="31100", province="TV"),
    City(name="Vicenza", postal_code="36100", province="VI"),
    City(name="Lecce", postal_code="73100", province="LE"),
)

STREETS = (
    "Via Roma",
    "Via Garibaldi",
    "Via Mazzini",
    "Corso Italia",
    "Via Dante Alighieri",
    "Viale della Repubblica",
    "Via dell'Industria",
    "Via dell'Artigianato",
    "Via Emilia",
    "Via Nazionale",
    "Piazza Cavour",
    "Via dei Mille",
)

NAME_FIRST = (
    "Elettro",
    "Idro",
    "Tecno",
    "Ferramenta",
    "Forniture",
    "Impianti",
    "Distribuzione",
    "Commerciale",
    "Edil",
    "Ufficio",
)
NAME_SECOND = (
    "Adriatica",
    "Padana",
    "Tirrena",
    "Lombarda",
    "Centro Italia",
    "Sud",
    "Nord Est",
    "Rossi",
    "Bianchi",
    "Ferri",
    "Galli",
    "Conti",
)
LEGAL_FORMS = ("S.r.l.", "S.p.A.", "S.n.c.", "S.a.s.", "S.r.l.s.")

# Mostly 22% goods; a few 10% and 4% items so invoices have multiple VAT buckets.
PRODUCTS = (
    Product(
        code="CV-325",
        description="Cavo elettrico FG16OR16 3x2,5 mm²",
        unit="m",
        min_price=Decimal("0.95"),
        max_price=Decimal("1.60"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="CV-315",
        description="Cavo elettrico FS17 1x1,5 mm² blu",
        unit="m",
        min_price=Decimal("0.18"),
        max_price=Decimal("0.35"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="IN-16A",
        description="Interruttore magnetotermico 1P+N 16A 4,5kA",
        unit="pz",
        min_price=Decimal("8.50"),
        max_price=Decimal("14.90"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="DF-25",
        description="Interruttore differenziale puro 2P 25A 30mA",
        unit="pz",
        min_price=Decimal("28.00"),
        max_price=Decimal("46.00"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="PR-S10",
        description="Presa schuko 10/16A bianca serie civile",
        unit="pz",
        min_price=Decimal("2.40"),
        max_price=Decimal("4.80"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="SC-503",
        description="Scatola da incasso 503 per 3 moduli",
        unit="pz",
        min_price=Decimal("0.35"),
        max_price=Decimal("0.70"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="TB-20",
        description="Tubo corrugato flessibile diametro 20 mm",
        unit="m",
        min_price=Decimal("0.22"),
        max_price=Decimal("0.45"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="LD-18W",
        description="Plafoniera LED 18W 4000K IP65",
        unit="pz",
        min_price=Decimal("12.00"),
        max_price=Decimal("24.00"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="LD-E27",
        description="Lampadina LED E27 10W luce calda",
        unit="pz",
        min_price=Decimal("1.90"),
        max_price=Decimal("3.90"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="QD-12M",
        description="Quadro elettrico da parete 12 moduli IP40",
        unit="pz",
        min_price=Decimal("18.00"),
        max_price=Decimal("32.00"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="MR-TP",
        description="Morsetto a leva 3 poli 0,2-4 mm²",
        unit="conf",
        min_price=Decimal("6.50"),
        max_price=Decimal("11.00"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="NS-CAV",
        description="Nastro isolante PVC 19 mm x 25 m nero",
        unit="pz",
        min_price=Decimal("0.80"),
        max_price=Decimal("1.70"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="VT-4X40",
        description="Viti autofilettanti 4x40 zincate",
        unit="conf",
        min_price=Decimal("3.20"),
        max_price=Decimal("6.40"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="TS-F6",
        description="Tassello in nylon 6 mm",
        unit="conf",
        min_price=Decimal("2.10"),
        max_price=Decimal("4.20"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="GU-NIT",
        description="Guanti da lavoro in nitrile taglia L",
        unit="conf",
        min_price=Decimal("4.90"),
        max_price=Decimal("8.90"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="CA-A4",
        description="Carta per fotocopie A4 80 g/m² risma 500 fogli",
        unit="pz",
        min_price=Decimal("3.40"),
        max_price=Decimal("5.20"),
        vat_rate=Decimal("22"),
    ),
    Product(
        code="MN-TEC",
        description="Manuale tecnico impianti elettrici civili",
        unit="pz",
        min_price=Decimal("24.00"),
        max_price=Decimal("39.00"),
        vat_rate=Decimal("4"),
    ),
    Product(
        code="NR-CEI",
        description="Guida alle norme CEI 64-8 edizione 2026",
        unit="pz",
        min_price=Decimal("45.00"),
        max_price=Decimal("68.00"),
        vat_rate=Decimal("4"),
    ),
    Product(
        code="BS-1KG",
        description="Biscotti frollini confezione 1 kg",
        unit="conf",
        min_price=Decimal("3.60"),
        max_price=Decimal("5.40"),
        vat_rate=Decimal("10"),
    ),
    Product(
        code="ZU-1KG",
        description="Zucchero semolato 1 kg",
        unit="pz",
        min_price=Decimal("0.95"),
        max_price=Decimal("1.60"),
        vat_rate=Decimal("10"),
    ),
)
